App\Diet\Domain\Model\Day:
  type: entity
  table: day
  repositoryClass: App\Diet\Domain\Repository\DayRepository
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
    date:
      column: date
      type: datetime
  manyToOne:
    period:
      targetEntity: App\Diet\Domain\Model\Period
      inversedBy: days
      joinColumn:
        name: period_id
        referencedColumnName: id
  oneToMany:
    meals:
      targetEntity: App\Diet\Domain\Model\Meal
      mappedBy: day