App\Diet\Domain\Model\Day:
  type: entity
  table: day
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
    date:
      column: date
      type: datetime
      unique: true
  manyToOne:
    period:
      targetEntity: App\Diet\Domain\Model\Period
      inversedBy: days
      joinColumn:
        name: period_id
        referencedColumnName: id
  manyToMany:
    meals:
      targetEntity: App\Diet\Domain\Model\Meal
      joinTable:
        name: meal_to_day
        joinColumns:
          day_id:
            referencedColumnName: id
        inverseJoinColumns:
          meal_id:
            referencedColumnName: id