App\Diet\Domain\Model\DietPlan:
  type: entity
  table: diet_plan
  id:
    id:
      type: uuid
      unique: true
  fields:
    daysQuantity:
      column: days_quantity
      type: integer
  manyToOne:
    dietType:
      targetEntity: App\Diet\Domain\Model\DietType
      inversedBy: dietPlans
      joinColumn:
        name: diet_type_id
        referencedColumnName: id
  oneToOne:
    owner:
      targetEntity: App\Diet\Domain\Model\Owner
      joinColumn:
        name: owner_id
        referencedColumnName: id