App\Diet\Domain\Model\DietPlan:
  type: entity
  table: diet_plan
  id:
    id:
      type: uuid
      unique: true
  fields:
    daysQuantity:
      column: days_quantity
      type: integer
  oneToOne:
    dietType:
      targetEntity: App\Diet\Domain\Model\DietType
      joinColumn:
        name: diet_type_id
        referencedColumnName: id