App\Diet\Domain\Model\DietType:
  type: entity
  table: diet_type
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
    description:
      column: description
      type: string
      nullable: true
    mealsQuantity:
      column: meals_quantity
      type: integer
  oneToMany:
    dietPlans:
      targetEntity: App\Diet\Domain\Model\DietPlan
      mappedBy: dietType