App\Diet\Domain\Model\MealType:
  type: entity
  table: meal_type
  repositoryClass: App\Diet\Domain\Repository\MealTypeRepository
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
    description:
      column: description
      type: string
      nullable: true