App\Diet\Domain\Model\MealType:
  type: entity
  table: meal_type
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
    description:
      column: description
      type: string
      nullable: true
  oneToMany:
    meals:
      targetEntity: App\Diet\Domain\Model\Meal
      mappedBy: mealType