App\Diet\Domain\Model\Period:
  type: entity
  table: period
  id:
    id:
      type: uuid
      unique: true
  manyToOne:
    dietPlan:
      targetEntity: DietPlan
      joinColumn:
        name: diet_plan_id
        referencedColumnName: id
  oneToMany:
    days:
      targetEntity: Day
      mappedBy: period
      orphanRemoval: true