App\Diet\Domain\Model\ProductType:
  type: entity
  table: product_type
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
    description:
      column: description
      type: string
      nullable: true
  oneToMany:
    products:
      targetEntity: App\Diet\Domain\Model\Product
      mappedBy: productType