App\Diet\Domain\Model\Product:
  type: entity
  table: product
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string
  manyToOne:
    productType:
      targetEntity: App\Diet\Domain\Model\ProductType
      inversedBy: products
      joinColumn:
        name: product_type_id
        referencedColumnName: id