App\Diet\Domain\Model\Product:
  type: entity
  table: product
  repositoryClass: App\Diet\Domain\Repository\ProductRepository
  id:
    id:
      type: uuid
      unique: true
  fields:
    name:
      column: name
      type: string