App\Diet\Domain\Model\Recipe:
  type: entity
  table: recipe
  id:
    id:
      type: uuid
      unique: true
  oneToMany:
    steps:
      targetEntity: App\Diet\Domain\Model\RecipeStep
      mappedBy: recipe
      orphanRemoval: true