App\Diet\Domain\Model\Recipe:
  type: entity
  table: recipe
  repositoryClass: App\Diet\Domain\Repository\RecipeRepository
  id:
    id:
      type: uuid
      unique: true
  fields:
    cookingTime:
      column: cooking_time
      type: integer
      nullable: true
  oneToMany:
    steps:
      targetEntity: App\Diet\Domain\Model\RecipeStep
      mappedBy: recipe
      orphanRemoval: true