parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Diet\Application\Command\GenerateDietHandler:
        public: true

    App\Diet\Application\Query\GetPeriodDietExecutor:
        public: true

    App\Diet\Application\Query\GetPeriodMealRecipeExecutor:
        public: true

    App\Diet\Application\Query\GetPeriodMealIngredientExecutor:
        public: true